export type LOGIN_FIRST_FACTOR = "LOGIN/FIRST_FACTOR";
export const LOGIN_FIRST_FACTOR: LOGIN_FIRST_FACTOR = "LOGIN/FIRST_FACTOR";

export type LOGIN_FIRST_FACTOR_RESULT = "LOGIN/FIRST_FACTOR_RESULT";
export const LOGIN_FIRST_FACTOR_RESULT: LOGIN_FIRST_FACTOR_RESULT = "LOGIN/FIRST_FACTOR_RESULT";

export type LOGIN_SECOND_FACTOR = "LOGIN/SECOND_FACTOR";
export const LOGIN_SECOND_FACTOR: LOGIN_SECOND_FACTOR = "LOGIN/SECOND_FACTOR";

export type LOGIN_SECOND_FACTOR_RESULT = "LOGIN/SECOND_FACTOR_RESULT";
export const LOGIN_SECOND_FACTOR_RESULT: LOGIN_SECOND_FACTOR_RESULT = "LOGIN/SECOND_FACTOR_RESULT";

export type LOGIN_CLEAR_CREDENTIALS = "LOGIN/CLEAR_CREDENTIALS";
export const LOGIN_CLEAR_CREDENTIALS: LOGIN_CLEAR_CREDENTIALS = "LOGIN/CLEAR_CREDENTIALS";

export type LOGIN_ERROR = "LOGIN/ERROR";
export const LOGIN_ERROR: LOGIN_ERROR = "LOGIN/ERROR";

export type LOGIN_CLEAR_ERROR = "LOGIN/CLEAR_ERROR";
export const LOGIN_CLEAR_ERROR: LOGIN_CLEAR_ERROR = "LOGIN/CLEAR_ERROR";

export type LOGIN_ABORT = "LOGIN/ABORT";
export const LOGIN_ABORT: LOGIN_ABORT = "LOGIN/ABORT";

export type LOGIN_REHYDRATE = "persist/REHYDRATE";
export const LOGIN_REHYDRATE: LOGIN_REHYDRATE = "persist/REHYDRATE";
