export type CHECK_FOR_UPDATES = "TOC/CHECK_FOR_UPDATES";
export const CHECK_FOR_UPDATES: CHECK_FOR_UPDATES = "TOC/CHECK_FOR_UPDATES";

export type UP_TO_DATE = "TOC/UP_TO_DATE";
export const UP_TO_DATE: UP_TO_DATE = "TOC/UP_TO_DATE";

export type NEW_VERSION_AVAILABLE = "TOC/NEW_VERSION_AVAILABLE";
export const NEW_VERSION_AVAILABLE: NEW_VERSION_AVAILABLE = "TOC/NEW_VERSION_AVAILABLE";

export type LOAD_NEW_TOC = "TOC/LOAD_NEW_TOC";
export const LOAD_NEW_TOC: LOAD_NEW_TOC = "TOC/LOAD_NEW_TOC";

export type ERROR_DOWNLOADING = "TOC/ERROR_DOWNLOADING";
export const ERROR_DOWNLOADING: ERROR_DOWNLOADING = "TOC/ERROR_DOWNLOADING";

export type DROP_PENDING_CHANGES = "TOC/DROP_PENDING_CHANGES";
export const DROP_PENDING_CHANGES: DROP_PENDING_CHANGES = "TOC/DROP_PENDING_CHANGES";
